version: "3.3"
services:

  # ubuntu server
  ubuntu:
    build: .
    container_name: webui_memoir_ubuntu_2024
    image: ubuntu
    restart: always
    command: ["sleep","infinity"]
    volumes:
      - './storage/ubuntu:/home/webui_memoir:rw'
    ports:
      - "5555:22"
    network_mode: bridge


